### PR TITLE
Always use lower case addresses in getPrivateKey comparison

### LINKED ISSUE #294: WalletSubprovider incorrectly compares private keys
I was trying to instantiate a new Provider using a private key and the only error I was getting was "Account not found", without any stacktrace or additional info.
I did some debugging and found the following code in `/subproviders/wallet.js`:
```
  opts.getPrivateKey = function (address, cb) {
    if (address !== wallet.getAddressString()) {
      return cb('Account not found')
    }

    cb(null, wallet.getPrivateKey())
  }
```
In my case `address` was almost the same as the return value of `wallet.getAddressString()` with the exception that some chars were of different casing (upper/lower case). As far as I know addresses in the blockchain should not be case sensitive. Is this a bug? Also maybe it would help to add additional info to the error returned in the callback, like values which failed at the comparison.

### PR DESCRIPTION
**Pull request by axic**
Fixes #294.

Most of the code considers the account list with `toLowerCase`. This changes ensures it happens in `wallet.js` too.

### CODE REVIEW

**Comment by victorbadila** [comment]
yes, let's merge this asap 👍

File: subproviders/wallet.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ function WalletSubprovider (wallet, opts) {
   }
 
   opts.getPrivateKey = function (address, cb) {
-    if (address !== wallet.getAddressString()) {
+    if (address.toLowerCase() !== wallet.getAddressString()) {
```
Comment (victorbadila) [inline subproviders/wallet.js]: if we are sure `wallet.getAddressString()` always returns a string would it make sense to call a `.toLowerCase()` on its result also?

Comment (axic) [reply subproviders/wallet.js]: It always returns a lowercase string. There is `getChecksummedAddressString()` for the checksummed one.

Comment (oprearocks) [reply subproviders/wallet.js]: I would add a check to see whether address has been provided, otherwise calling `toLowerCase()` on anything other than a string will throw.

Would also store the result of `wallet.getAddressString()` in a variable.

**Comment by axic** [comment]
Ping @kumavis @danfinlay 😉

**Comment by kumavis** [comment]
thanks @axic, sorry for delay

**Comment by axic** [comment]
Thanks!
